### ISSUE TITLE
Wrong parameters of BWR in README examples

### ISSUE THREAD

**Issue by ShreyaAN10** [TrafficSliver/splitting_simulator#1]
According to `getWeights()` in file `multipath.py`, number of alpha values must be equal to the number of circuits i.e `m`

```
def getWeights(n,alphas):
	aph = alphas.split(',')
	if (len(aph) != n):
		return -1
	vec_alphas = np.array(aph,dtype= np.float)
	w = np.random.dirichlet(vec_alphas,size=1)[0]
	return w
```

However, the example uses `m=5` but sets option `-a` parameters to `1,1`, resulting in the following error:
```
user>> python simulator.py -p /share/s4an/datasets/bigenough/undefended/monitored/standard/ -m 5 -o data/bwr_5m_bestd/ -s batched_weighted_random -r 50,70 -a 1,1

Simulating BWR multi-path scheme...
Traceback (most recent call last):
  File "simulator.py", line 503, in <module>
    sim_bwr(paths_, latencies_,traces_,outfolder_,range_, alpha_)
  File "simulator.py", line 206, in sim_bwr
    last_client_route =  np.random.choice(np.arange(0,n),p = w_out)
  File "mtrand.pyx", line 911, in numpy.random.mtrand.RandomState.choice
TypeError: object of type 'int' has no len()
```

Resolved the error by using `1,1,1,1,1` instead.

**Comment by amitseva** [comment]
Thanks for your comment. We will update the README file.
